<?php

/**
 * Codey srcset ladders (core) — THE CANONICAL LADDER, AS A TEMPLATE TO COPY.
 *
 * Copy the array below into your project's config.php under
 * `thumbs.srcsets` and add your own ladders beside it. Do NOT `require` this
 * file from config.php.
 *
 * That was the first shape and it was wrong. config.php must boot from itself
 * alone: a require reaches out of the project into a tree that a Codey update
 * overwrites wholesale, and that a `kirby` CLI scaffold run after cloning can
 * replace or delete outright. When a stylesheet goes missing the site looks
 * wrong; when config.php's require target goes missing the site does not boot.
 * Config is the wrong layer to hold a dependency on core.
 *
 * So this file is read by nothing at runtime. It exists to be the one place
 * the RULE below is written down, and the thing a new project pastes from.
 *
 * ── THE RULE THIS FILE EXISTS TO ENFORCE ──────────────────────────────
 *
 * THE ARRAY KEY IS THE SRCSET DESCRIPTOR Kirby writes into the markup, and the
 * browser trusts it absolutely — it never measures the file. So the key MUST
 * equal the width beside it. A ladder that ships '2000w' => ['width' => 2200]
 * tells every browser the file is 10% narrower than it is, and they select
 * accordingly. That bug is invisible in the Panel, invisible in the rendered
 * page, and only shows up if you compare a descriptor against the file it
 * names — which is why the rule lives in core rather than in a comment on a
 * project's config.
 *
 * Steps are ~1.33x apart: close enough that the chosen candidate is never much
 * bigger than the slot, far enough apart that the thumb count stays sane. All
 * three ladders are identical so the avif / webp / fallback paths cannot
 * disagree about which widths exist.
 *
 * ── THE VALUES, WHICH ARE YOURS ───────────────────────────────────────
 *
 * Widths, qualities and the 2560 ceiling are DEFAULTS, not doctrine. The
 * ceiling is only correct if your masters reach it: KIRBY DOES NOT UPSCALE, so
 * a master narrower than a step silently yields a smaller file while the
 * descriptor still claims the full width — the same lie as above, per-image.
 *
 * If your masters are smaller, drop the top steps rather than shipping
 * descriptors that overstate them. Override by merging your own array over
 * this one in config.php; do not edit this file — it is overwritten wholesale
 * on a Codey update.
 */

return [
    'default' => [
        '400w'  => ['width' => 400],
        '600w'  => ['width' => 600],
        '900w'  => ['width' => 900],
        '1200w' => ['width' => 1200],
        '1600w' => ['width' => 1600],
        '2000w' => ['width' => 2000],
        '2560w' => ['width' => 2560],
    ],
    'webp' => [
        '400w'  => ['width' => 400,  'format' => 'webp', 'quality' => 75],
        '600w'  => ['width' => 600,  'format' => 'webp', 'quality' => 75],
        '900w'  => ['width' => 900,  'format' => 'webp', 'quality' => 75],
        '1200w' => ['width' => 1200, 'format' => 'webp', 'quality' => 75],
        '1600w' => ['width' => 1600, 'format' => 'webp', 'quality' => 75],
        '2000w' => ['width' => 2000, 'format' => 'webp', 'quality' => 75],
        '2560w' => ['width' => 2560, 'format' => 'webp', 'quality' => 75],
    ],
    'avif' => [
        '400w'  => ['width' => 400,  'format' => 'avif', 'quality' => 75],
        '600w'  => ['width' => 600,  'format' => 'avif', 'quality' => 75],
        '900w'  => ['width' => 900,  'format' => 'avif', 'quality' => 75],
        '1200w' => ['width' => 1200, 'format' => 'avif', 'quality' => 75],
        '1600w' => ['width' => 1600, 'format' => 'avif', 'quality' => 75],
        '2000w' => ['width' => 2000, 'format' => 'avif', 'quality' => 75],
        '2560w' => ['width' => 2560, 'format' => 'avif', 'quality' => 75],
    ],
];
