#!/usr/bin/env node
/**
 * ════════════════════════════════════════════════════════════════════════
 *  codey-palette.cjs — GENERATE YOUR BRAND PALETTE
 *
 *  QUICK USE (run from your project root):
 *
 *    node codey-palette.cjs --dark "#111318" --light "#f6f8fb" --mid "#c8452f"
 *
 *  → writes src/assets/css/_brand-palette.css
 *  → then add  @import "./_brand-palette.css";  to src/assets/css/main.css
 *    (after codey/index.css) and put your theme class on <body>.
 *
 *    node codey-palette.cjs            # no args: print every option
 *
 *  --dark / --light are the two poles of your brand's spectrum (required).
 *  --mid is your brand's vivid colour; it keeps the mid-tones from washing out.
 *  Add --half 1.5,2.5 for half steps (--color-15, --color-25).
 *
 *  This file is PLACED HERE BY codey-sync and is overwritten on every
 *  composer install/update, so it always matches the installed version.
 *  Don't edit it — pass flags instead.
 * ════════════════════════════════════════════════════════════════════════
 *
 * codey brand-palette — generate a perceptually even brand palette in OKLCH
 * from the TWO POLES of a colour spectrum.
 *
 * Scale orientation: 0 = DARKEST → 9 = LIGHTEST — "least light → most light".
 * This is the convention across the whole system; the shipped sample palette
 * package/css/palettes/_codey.css is generated by this script and follows it.
 *
 * Interpolation happens in OKLCH, so the steps are perceptually even rather
 * than evenly spaced in sRGB — mid-tones don't go muddy the way a naive hex
 * lerp does. Hue takes the shortest arc between the poles.
 *
 * OUTPUT LOCATION: writes OUTSIDE the codey/ zones — by default
 * src/assets/css/_brand-palette.css — because it is a PROJECT-OWNED brand
 * artefact. Never write it into src/assets/css/codey/, which is wiped on sync.
 *
 * Usage:
 *   node brand-palette.cjs --dark "#0f151b" --light "#eef6fe" \
 *        [--mid "#1fa7f3"] [--cusp] [--gamut p3|srgb] \
 *        [--half 1.5,2.5] [--scope ".theme-brand"] [--prefix color] \
 *        [--steps 10] [--out src/assets/css/_brand-palette.css] [--stdout]
 *
 * Half steps: the decimal point is dropped, so --half 1.5,2.5 emits
 *   --color-15 and --color-25 (matching the codey palette's dark-end steps).
 */
"use strict";
const fs = require("fs");
const path = require("path");

/* ── colour maths ───────────────────────────────────────────────────── */

function parseHex(input) {
  const s = String(input).trim().replace(/^#/, "");
  const hex = s.length === 3 ? s.split("").map((c) => c + c).join("") : s;
  if (!/^[0-9a-fA-F]{6}$/.test(hex)) {
    throw new Error(`not a hex colour: "${input}" (expected #rgb or #rrggbb)`);
  }
  return [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16));
}

const srgbToLinear = (c) => {
  c /= 255;
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
};

/** linear sRGB → OKLab (Björn Ottosson) */
function linearToOklab(r, g, b) {
  const l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b;
  const m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b;
  const s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b;
  const l_ = Math.cbrt(l), m_ = Math.cbrt(m), s_ = Math.cbrt(s);
  return {
    L: 0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_,
    a: 1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_,
    b: 0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_,
  };
}

function hexToOklch(hex) {
  const [r, g, b] = parseHex(hex).map(srgbToLinear);
  const { L, a, b: bb } = linearToOklab(r, g, b);
  const C = Math.hypot(a, bb);
  let H = (Math.atan2(bb, a) * 180) / Math.PI;
  if (H < 0) H += 360;
  return { L, C, H };
}

/** OKLab → linear sRGB (inverse of Ottosson's matrices) */
function oklabToLinearSrgb(L, a, b) {
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

/** OKLab → XYZ (D65) — via the inverse of Ottosson's M1 */
function oklabToXyz(L, a, b) {
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3;
  return [
     1.2270138511 * l - 0.5577999807 * m + 0.281256149  * s,
    -0.0405801784 * l + 1.1122568696 * m - 0.0716766787 * s,
    -0.0763812845 * l - 0.4214819784 * m + 1.5861632204 * s,
  ];
}

/** XYZ (D65) → linear Display P3 */
function xyzToLinearP3([X, Y, Z]) {
  return [
     2.4934969119 * X - 0.9313836179 * Y - 0.4027107845 * Z,
    -0.8294889696 * X + 1.7626640603 * Y + 0.0236246858 * Z,
     0.0358458302 * X - 0.0761723893 * Y + 0.956884524  * Z,
  ];
}

/**
 * Is this colour displayable in the target gamut?
 * Default target is DISPLAY P3 — the native gamut of most current hardware.
 * Clamping to sRGB throws away chroma those screens can actually show.
 * (Note: legacy hex/rgb() values are still interpreted as sRGB; oklch() is
 * device-independent, which is why it can address the wider gamut at all.)
 */
const inGamut = ({ L, C, H }, space = "p3") => {
  const h = (H * Math.PI) / 180;
  const a = C * Math.cos(h), b = C * Math.sin(h);
  const rgb = space === "srgb"
    ? oklabToLinearSrgb(L, a, b)
    : xyzToLinearP3(oklabToXyz(L, a, b));
  return rgb.every((c) => c >= -1e-4 && c <= 1 + 1e-4);
};

/**
 * Maximum in-gamut chroma for a given L and H — the "cusp" of the target gamut
 * at that lightness. Binary search is robust and accurate to 1e-4 without
 * needing Ottosson's analytic cusp solver.
 */
function maxChroma(L, H, space = "p3") {
  let lo = 0, hi = 0.5;
  for (let i = 0; i < 32; i++) {
    const mid = (lo + hi) / 2;
    if (inGamut({ L, C: mid, H }, space)) lo = mid; else hi = mid;
  }
  return lo;
}

/** Clamp into the target gamut by reducing chroma only (preserves L and H). */
function toGamut(c, space = "p3") {
  if (inGamut(c, space)) return { ...c, clipped: false };
  return { ...c, C: maxChroma(c.L, c.H, space), clipped: true };
}

/** shortest-arc hue interpolation */
function lerpHue(h1, h2, t) {
  let d = ((h2 - h1 + 540) % 360) - 180;
  return (h1 + d * t + 360) % 360;
}

/**
 * Interpolate between the poles at t (0 = dark, 1 = light).
 *
 * `midC` bows the CHROMA toward the middle of the ramp. Both poles of a brand
 * spectrum are usually near-neutral (a near-black and a near-white, C≈0.015),
 * so a plain linear mix yields a flat, washed-out ramp with no colour in it.
 * Real palettes peak in chroma around the mid-tones — codey's own #1fa7f3 sits
 * at C≈0.154 between poles of C≈0.015.
 *
 * midC is an ABSOLUTE target, not a multiplier: sin(πt) tapers to 0 at both
 * ends (so the poles keep their own chroma) and reaches 1 at t=0.5, where the
 * curve lands exactly on midC.
 */
function lerp2(a, b, t) {
  // An achromatic pole has no meaningful hue — borrow the other end's.
  const aH = a.C < 1e-4 ? b.H : a.H;
  const bH = b.C < 1e-4 ? a.H : b.H;
  return {
    L: a.L + (b.L - a.L) * t,
    C: a.C + (b.C - a.C) * t,
    H: lerpHue(aH, bH, t),
  };
}

/**
 * Build the ramp colour at t (0 = dark pole, 1 = light pole).
 *
 * Three ways to get a RICH CENTRE rather than a washed-out linear ramp — both
 * poles of a brand spectrum are near-neutral (C≈0.015), so a plain lerp has no
 * colour in the middle:
 *
 *   opts.mid   — THREE-POINT anchor. Interpolate dark→mid→light through the
 *                brand's actual vivid colour. Most faithful: it reproduces a
 *                hand-built palette exactly, because you supply the real
 *                mid-tone rather than describing it.
 *   opts.cusp  — GAMUT-CUSP riding. Push chroma to the maximum the target gamut
 *                (P3 by default) can hold at each lightness, scaled by sin(πt)
 *                so the poles stay neutral. Richest displayable ramp.
 *   opts.midC  — absolute chroma target at the midpoint (simple bell curve).
 *
 * Everything is finally clamped into the target gamut by reducing chroma only,
 * so no step is left for the browser to clip unpredictably.
 */
function ramp(dark, light, t, opts) {
  let c;
  if (opts.mid) {
    // piecewise: dark→mid over [0,0.5], mid→light over [0.5,1]
    c = t <= 0.5
      ? lerp2(dark, opts.mid, t / 0.5)
      : lerp2(opts.mid, light, (t - 0.5) / 0.5);
  } else {
    c = lerp2(dark, light, t);
    if (opts.cusp) {
      const peak = maxChroma(c.L, c.H, opts.gamut);
      c = { ...c, C: c.C + (peak - c.C) * Math.sin(Math.PI * t) };
    } else if (opts.midC != null) {
      const baseMid = (dark.C + light.C) / 2;
      c = { ...c, C: Math.max(0, c.C + (opts.midC - baseMid) * Math.sin(Math.PI * t)) };
    }
  }
  return toGamut(c, opts.gamut);
}

const fmt = ({ L, C, H }) =>
  `oklch(${(L * 100).toFixed(2)}% ${C.toFixed(4)} ${H.toFixed(2)})`;

/* ── cli ────────────────────────────────────────────────────────────── */

function parseArgs(argv) {
  const a = { steps: 10, scope: ":root", prefix: "color", half: [], stdout: false,
              midC: null, mid: null, cusp: false, gamut: "p3" };
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i];
    if (k === "--dark") a.dark = argv[++i];
    else if (k === "--light") a.light = argv[++i];
    else if (k === "--steps") a.steps = parseInt(argv[++i], 10);
    else if (k === "--scope") a.scope = argv[++i];
    else if (k === "--prefix") a.prefix = argv[++i];
    else if (k === "--out") a.out = argv[++i];
    else if (k === "--stdout") a.stdout = true;
    else if (k === "--mid-chroma") a.midC = parseFloat(argv[++i]);
    else if (k === "--mid") a.mid = argv[++i];
    else if (k === "--cusp") a.cusp = true;
    else if (k === "--gamut") a.gamut = String(argv[++i]).toLowerCase();
    else if (k === "--half") {
      a.half = String(argv[++i]).split(",").map((s) => parseFloat(s.trim())).filter((n) => !isNaN(n));
    }
  }
  return a;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.dark || !args.light) {
    console.error(
      "codey brand-palette — generate an OKLCH brand palette from two poles.\n\n" +
      "  --dark <hex>    darkest pole  → step 0   (required)\n" +
      "  --light <hex>   lightest pole → step N-1 (required)\n" +
      "  --steps <n>     number of whole steps (default 10 → 0…9)\n" +
      "  --half <list>   half steps, e.g. 1.5,2.5 → --color-15, --color-25\n" +
      "  --mid <hex>     THREE-POINT anchor: the brand's vivid mid colour;\n" +
      "                  interpolates dark->mid->light (most faithful)\n" +
      "  --cusp          ride the gamut cusp — richest displayable ramp\n" +
      "  --gamut <p3|srgb> clamp target (default p3 — modern displays;\n" +
      "                  use srgb only if you must stay in the legacy gamut)\n" +
      "  --mid-chroma <n> absolute chroma at the midpoint — bows the ramp so\n" +
      "                  mid-tones stay vivid (poles keep their own chroma).\n" +
      "                  Typical: 0.10 muted · 0.15 vivid · 0.20 saturated.\n" +
      "                  Omit for a flat linear ramp.\n" +
      "  --scope <sel>   CSS selector to scope to (default :root)\n" +
      "  --prefix <name> custom-property prefix (default color)\n" +
      "  --out <path>    output file (default src/assets/css/_brand-palette.css)\n" +
      "  --stdout        print instead of writing\n"
    );
    process.exit(1);
  }

  const dark = hexToOklch(args.dark);
  const light = hexToOklch(args.light);
  const last = args.steps - 1;
  const opts = {
    mid:  args.mid ? hexToOklch(args.mid) : null,
    cusp: args.cusp,
    midC: args.midC,
    gamut: args.gamut === "srgb" ? "srgb" : "p3",
  };

  // whole steps: 0 = darkest → last = lightest
  const rows = [];
  for (let i = 0; i <= last; i++) {
    rows.push({ name: `${i}`, pos: i, color: ramp(dark, light, i / last, opts) });
  }
  // half steps: 6.5 → "65"
  for (const h of args.half) {
    if (h <= 0 || h >= last) continue;
    rows.push({
      name: String(h).replace(".", ""),
      pos: h,
      color: ramp(dark, light, h / last, opts),
    });
  }
  rows.sort((x, y) => x.pos - y.pos);

  const pad = Math.max(...rows.map((r) => r.name.length));
  const lines = rows.map((r) => {
    const label =
      r.pos === 0 ? "  /* darkest */" : r.pos === last ? "  /* lightest */" : "";
    return `  --${args.prefix}-${r.name.padEnd(pad)}: ${fmt(r.color)};${label}`;
  });

  const css = `/* ════════════════════════════════════════════════════════════════════
   BRAND PALETTE — GENERATED, do not edit by hand.

   Regenerate with:
     node <codey>/package/scripts/brand-palette.cjs \\
       --dark "${args.dark}" --light "${args.light}"${args.half.length ? ` --half ${args.half.join(",")}` : ""}

   Scale: 0 = DARKEST → ${last} = LIGHTEST. Steps are interpolated in OKLCH, so
   they are perceptually even; hue follows the shortest arc between the poles.
   Chroma is clamped to the ${opts.gamut.toUpperCase()} gamut.

   PROJECT-OWNED: this file lives outside the codey/ zones and is never
   touched by codey-sync. Map these raw steps to semantic tokens (--color-text,
   --link, …) in your theme layer.
   ════════════════════════════════════════════════════════════════════ */

${args.scope} {
${lines.join("\n")}
}
`;

  if (args.stdout) {
    process.stdout.write(css);
    return;
  }
  const out = path.resolve(args.out || "src/assets/css/_brand-palette.css");
  if (/[\\/]codey[\\/]/.test(out)) {
    console.error(
      `codey brand-palette: refusing to write into a synced codey/ zone:\n  ${out}\n` +
      `That folder is wiped on every sync. Write to a project-owned path instead.`
    );
    process.exit(1);
  }
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, css);
  console.log(`brand-palette: wrote ${rows.length} steps → ${out}`);
}

main();
